version: "3"
services:
  adso_server:
    container_name: adso_server
    restart: always
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    links:
      - postgres
#   web:
#     container_name: web_sela
#     restart: always
#     build: ./web
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./web:/app
  postgres:
    container_name: postgres_sela
    image: postgres:11.5-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: graphql-db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_sela
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres:
  pgadmin: